Updated SystemD / SysV / Upstart scripts

diff --git a/docs/sysvinit/clusterstatd b/docs/sysvinit/clusterstatd
--- a/docs/sysvinit/clusterstatd
+++ b/docs/sysvinit/clusterstatd
@@ -10,22 +10,22 @@
 ### END INIT INFO
 
 PHP=$(which php)
-DAEMON="/usr/share/clusterstat-daemon/clusterstatd.php"
+SCRIPT="/usr/share/clusterstat-daemon/clusterstatd.php"
 NAME="ClusterStat Daemon"
 
 test $PHP || { echo "PHP is not found"; exit 0; }
 test -x $PHP || { echo "PHP is not executable: $PHP"; exit 0; }
-test -f $DAEMON || { echo "Main ClusterStatD script not found: $DAEMON"; exit 0; }
+test -f $SCRIPT || { echo "Main ClusterStatD script not found: $SCRIPT"; exit 0; }
 
 set -e
 
 start() {
         echo "Starting $NAME ..."
-        $PHP $DAEMON start
+        $PHP -d disable_functions= -f $SCRIPT -- start
 }
 stop() {
         echo "Stopping $NAME ..."
-        $PHP $DAEMON stop
+        $PHP -d disable_functions= -f $SCRIPT -- stop
 }
 restart() {
         echo "Restarting $NAME..."
